### ISSUE TITLE
Authantication not working.

### ISSUE THREAD

**Issue by jayquantum** [nfscan/ios-receipt-scan-example#5]
Hello,

I have follow all steps and then run project into xcode with iphone. but I cant proceed further because I am getting success: false in response. Please help me is there anything I am missing ?
http://localhost:8080/nfscan-server/fe/taxreceipts/process/auth.action

**Comment by PauloMigAlmeida** [comment]
Hi @jayquantum,

There are just a few reasons why it's returning `success:false` in that endpoint. Either it's failing to validate your signature, which I seriously doubt, or you may have missed out some configuration step when setting up your development environment.

https://github.com/nfscan/nfscan/blob/master/02-Sourcecode/nfscan-server/src/main/java/cc/nfscan/server/controller/fe/TaxReceiptMobileController.java#L133-L150

Make sure you've followed every single step described on: https://github.com/nfscan/nfscan/wiki/Develpment-environment---%5BPortuguese%5D

Anyway, could you provide your console output so that I can have a way to check what's going on ?

**Comment by jayquantum** [comment]
Hi PauloMigAlmeida,

Thanks for reply. Please check below response which get from netbeans when I do Build. Let me know if you want anything else. I am running code into localhost. and also I am passing username: admin  password: admin  into header authentication when I call api. 

ant -f /Library/Tomcat/webapps/nfscan-server -Dbrowser.context=/Library/Tomcat/webapps/nfscan-server -DforceRedeploy=false -Dnb.internal.action.name=build dist
init:
deps-module-jar:
deps-ear-jar:
deps-jar:
Copying 153 files to /Library/Tomcat/webapps/nfscan-server/build/web
Copied 43 empty directories to 3 empty directories under /Library/Tomcat/webapps/nfscan-server/build/web
library-inclusion-in-archive:
library-inclusion-in-manifest:
Created dir: /Library/Tomcat/webapps/nfscan-server/build/empty
Created dir: /Library/Tomcat/webapps/nfscan-server/build/generated-sources/ap-source-output
compile:
compile-jsps:
Created dir: /Library/Tomcat/webapps/nfscan-server/dist
Building jar: /Library/Tomcat/webapps/nfscan-server/dist/nfscan-server.war
do-dist:
dist:
BUILD SUCCESSFUL (total time: 28 seconds)

**Comment by PauloMigAlmeida** [comment]
Hi @jayquantum 

The log you've pasted here is the build process from netbeans. it just tells you that whether it has compiled or not. However what I need in order to provide your a better support is the console output from the web server which you'll likely get when you're running it.

I've also noticed that you mentioned about sending something through the authentication header. There is no such thing on nfscan. All API calls are public available. Please take a look at this document:

https://github.com/nfscan/nfscan/wiki/Public-API-calls-%5BPortuguese%5D

**Comment by jayquantum** [comment]
Hi,

I am getting {"success":false} this output when I calling api. http://localhost:8080/nfscan-server/fe/taxreceipts/process/auth.action using POST method. as you say I have removed authentication header but output was same. let me know if you want anything else. If this not what you want then please let me know how can I get console output which you want if possible then please write steps to find it.

Do i need to do anything from below link.? Because I have not do anything from that. 
https://github.com/nfscan/ocr-process-service 

Thanks.

**Comment by PauloMigAlmeida** [comment]
Hi @jayquantum 

The output you've provided me is the http response form he API. What I need it the console output from the Servlet container, Tomcat in this case. Once more I'll kindly ask you to take a look at your development environment and check for java exceptions that can help me out figure out what's happening. I've a guess that you likely forgot to configure something to get this error, but I can only be sure that's the case when you paste the console output here.

Thanks
